### ISSUE TITLE
Intégrer Firebase

### ISSUE THREAD

**Issue by jefBinomed** [GDG-Nantes/DevQuest#11]

**Comment by jlandure** [comment]
t'es sur de ça ? c'est hyper cher dès que tu as plein de connexions simultanées...

**Comment by jefBinomed** [comment]
bah théoriquement si Alexis joue le jeux,j'aurais droit à un quota temporaire élevé :) J'ai demandé à Alexis avant qu'il parte s'il pouvait me négocier ça et il était partant :). J'attends juste de bien brancher le truc avant et puis au pire, les gens le sauront pas :D

**Comment by jlandure** [comment]
pour info on a 500$ de crédit si on veut jouer avec !
tu voulais utiliser firebase pour quoi ? un classement temps-reel ? tout
stocker ?

**Comment by jefBinomed** [comment]
J'ai intégré firebase pour afficher en temps réel les joueurs qui jouent en même temps que toi :)

Et sinon pour les 500$, on en aura pas besoin car j'ai demandé à Alexis une évolution du plan utilisé pour DevQuest sur le temps de la journée :)
